apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: demo
  addonComponents:
    tracing:
      enabled: true
  values:
    global:
      jwtPolicy: first-party-jwt
      proxy:
        tracer: "lightstep"
      tracer:
        lightstep:
          # Point to a Microsat: https://docs.lightstep.com/docs/docker-install-and-configure-micro-satellites
          address: "169.254.186.180:8383"
          accessToken: "your-token-here"
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 100