extensions:
  health_check:

receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:55681
        cors_allowed_origins:
          - '*'
      grpc:
        endpoint: 0.0.0.0:55680

processors:
  batch:

exporters:
  logging:
#    loglevel: debug

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers:
      - otlp
      processors:
      - batch
      exporters:
      - logging

    traces:
      receivers:
      - otlp
      processors: 
      - batch
      exporters:
      - logging