extensions:
  health_check:

receivers:
  generator:
    path: /Users/claysmith/workspace/lightstep-partner-sdk/generator/config/hipster_shop.json
    #path: /Users/claysmith/workspace/lightstep-partner-sdk/generator/config/singleton_service.json
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:55681
        cors_allowed_origins:
          - '*'
      grpc:
        endpoint: 0.0.0.0:55680

processors:
  batch:

exporters:
  service:
    scraper:
      endpoint: 0.0.0.0:55688
  logging:
    loglevel: debug

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers:
      - otlp
      processors:
      - batch
      exporters:
      - logging

    traces:
      receivers:
      - otlp
      - generator
      processors: 
      - batch
      exporters:
      - service
      - logging