extensions:
  health_check:

receivers:
  # Pull traces from different Lightstep streams
  lightstep-streams/web-demo:
    organization: schuler-00fb47fa
    project: schuler-dev-00fb47fa
    api_key: "${LIGHTSTEP_API_KEY}"
    window_size: 5m
    stream_id: Pdt5RWjr

  lightstep-streams/service-discovery:
    organization: schuler-00fb47fa
    project: schuler-dev-00fb47fa
    api_key: "${LIGHTSTEP_API_KEY}"
    window_size: 5m
    stream_id: D5SxdRBg

  lightstep-streams/app-rabbit:
    organization: schuler-00fb47fa
    project: schuler-dev-00fb47fa
    api_key: "${LIGHTSTEP_API_KEY}"
    window_size: 5m
    stream_id: mTyDncv1

  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:55681
        cors_allowed_origins:
          - '*'
      grpc:
        endpoint: 0.0.0.0:55680

processors:
  batch:


exporters:
  service:
    scraper:
      endpoint: 0.0.0.0:55688
  logging:
  # Export to Lightstep Public Satellites
  otlp:
    endpoint: ingest.lightstep.com:443
    insecure_skip_verify: true
    headers:
      "lightstep-access-token": "${LS_ACCESS_TOKEN}"

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers:
        - lightstep-streams/web-demo
        - lightstep-streams/service-discovery
        - lightstep-streams/app-rabbit
      processors:
        - batch
      exporters:
        - logging
        - service