version: "3"
services:
  collector:
    image: otel/opentelemetry-collector-contrib-dev:latest
    environment:
      - LS_ACCESS_TOKEN=${LS_ACCESS_TOKEN}
    volumes:
      - ./conf/collector.yml:/etc/otel/config.yaml
  nginx:
    container_name: otel-nginx-test
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/otel-nginx.toml:/conf/otel-nginx.toml
      - ./files:/var/www/html/files
    ports:
      - "8000:8000"
    command:
      - /usr/sbin/nginx
      - -g
      - daemon off;
  node-backend:
    image: alchen99/express-hello:latest
