version: "3"
services:
  collector:
    image: otel/opentelemetry-collector-contrib:0.35.0
    environment:
      - LS_ACCESS_TOKEN=${LS_ACCESS_TOKEN}
    volumes:
      - ./conf/collector.yml:/etc/otel/config.yaml
  nginx:
    container_name: otel-nginx-test
    depends_on:
      - demo
      - collector
    image: ghcr.io/lightstep/lightstep-partner-toolkit-otel-nginx:latest
    # Uncomment below to build the nginx otel image (warning: takes ~20-25 minutes)
    # build:
    #  context: .
    #  dockerfile: Dockerfile
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/otel-nginx.toml:/conf/otel-nginx.toml
      - ./files:/var/www/html/files
    ports:
      - "8000:8000"
    command:
      - /usr/sbin/nginx
      - -g
      - daemon off;
  demo:
    container_name: ls-partner-sdk-demo
    environment:
      - LS_ACCESS_TOKEN=${LS_ACCESS_TOKEN}
      - SPLIT_API_KEY=${SPLIT_API_KEY}
      - ROLLBAR_POST_ITEM_KEY=${ROLLBAR_POST_ITEM_KEY}
    build:
      context: ../../demo/
    ports:
      - "8181:8181"
