version: "3.7"

services:
  go-opentelemetry-server:
    container_name: go-opentelemetry-server
    image: ghcr.io/lightstep/opentelemetry-examples:go-opentelemetry-server
    depends_on:
      - collector
    environment:
      - LS_SATELLITE_URL=collector:55680
      - LS_INSECURE=1
      - LS_SERVICE_NAME=go-opentelemetry-server
      - LS_SERVICE_VERSION=9.9.1
    stop_grace_period: 1s

  go-opentelemetry-client:
    container_name: go-opentelemetry-client
    image: ghcr.io/lightstep/opentelemetry-examples:go-opentelemetry-client
    depends_on:
      - go-opentelemetry-server
      - collector
    environment:
      - LS_SATELLITE_URL=collector:55680
      - LS_INSECURE=1
      - LS_SERVICE_NAME=go-opentelemetry-client
      - LS_SERVICE_VERSION=9.9.2
      - DESTINATION_URL=http://go-opentelemetry-server:8081/ping
    stop_grace_period: 1s

  localtunnel-metric-webhook:
    image: efrecon/localtunnel
    depends_on:
      - collector
    command:
      --local-host collector --port 7071

  localtunnel-trace-webhook:
    image: efrecon/localtunnel
    depends_on:
      - collector
    command:
      --local-host collector --port 7070

  collector:
    container_name: ls-partner-collector
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LS_ACCESS_TOKEN=${LS_ACCESS_TOKEN}
    volumes:
      - ./config/collector-config.yml:/otel/collector-config.yml
    ports:
      - "13133:13133" # health_check
      - "55680:55680" # otlp
      - "7070:7070" # traces pipeline webhook
      - "7071:7071" # metrics pipeline webhook
